package com.shelfshare.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data; // for getters and setters

@Data // This automatically generates Getters and Setters
@Document(collection = "books") // This tells MongoDB to store this in a "books" table
public class Book {
    @Id
    private String id;          // Unique ID generated by MongoDB
    private String title;
    private String author;
    private String ownerId;     // The Bennett Enrollment ID (e.g., 23BTCS001)
    private String borrowerId;  // The ID of the student borrowing it
    private String status;      // "AVAILABLE", "PENDING", or "ON_LOAN"
}