spring.application.name=backend

spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.jfckkmc.mongodb.net/?appName=Cluster0
spring.mongodb.database=shelfshare

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys

#debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG