spring.application.name=backend


spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.jfckkmc.mongodb.net/?appName=Cluster0

spring.mongodb.database=shelfshare

#debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG