spring.application.name=backend
# Connect to your local MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/shelfshare

# This tells Spring to create the "shelfshare" database if it doesn't exist
spring.data.mongodb.database=shelfshare

# Show the MongoDB queries in the terminal (helpful for debugging)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG